import Head from 'next/head';
import FeaturedPost from '../components/FeaturedPost';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <FeaturedPost
          postSummary={{
            id: 42,
            slug: 'como-fazer-x-coisas-com-react-js',
            title: 'Como fazer X coisas com React.js',
            imageUrls: {
              default: '/laptop.jpeg',
              small: '/laptop.jpeg',
              medium: '/laptop.jpeg',
              large: '/laptop.jpeg',
            },
            editor: {
              id: 29,
              name: 'Daniel Bonifacio',
              avatarUrls: {
                default:
                  'https://storage.googleapis.com/alganews-files/posts/avatar-joao.jpeg',
                small:
                  'https://storage.googleapis.com/alganews-files/posts/avatar-joao-small.jpeg',
                medium:
                  'https://storage.googleapis.com/alganews-files/posts/avatar-joao-medium.jpeg',
                large:
                  'https://storage.googleapis.com/alganews-files/posts/avatar-joao-large.jpeg',
              },
              createdAt: '2017-03-04T00:12:45Z',
            },
            createdAt: '2020-12-01T18:09:02Z',
            updatedAt: '2023-01-03T21:10:06.931Z',
            published: true,
            tags: ['JavaScript'],
            canBePublished: true,
            canBeUnpublished: true,
            canBeDeleted: true,
            canBeEdited: true,
          }}
        ></FeaturedPost>
      </main>
    </div>
  );
}
